name: authenticate platform

on:
  workflow_call:
    inputs:
      target_platform:
        required: true
        type: string

jobs:
  build_platform:
    name: authenticate - ${{ github.event.inputs.target_platform }}
    runs-on: ubuntu-latest
    env:
      zone: ${{ github.event.inputs.target_platform }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2



