name: build platform

on:
  workflow_call:
    inputs:
      target_platform:
        required: true
        type: string

jobs:
  build_platform:
    name: deploy - ${{ github.event.inputs.target_platform }}
    runs-on: ubuntu-latest
    env:
      zone: ${{ github.event.inputs.target_platform }}
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Checkout
        uses: actions/checkout@v3        
      
      - name: Terraform Init
        id: init
        run: terraform init -reconfigure -backend-config="key=workflow-$zone"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var "env=$zone"


