
name: build and deploy platform

on:
  workflow_dispatch:
    inputs:
      target_platform_dev:
        description: 'Target Platform'
        required: true
        default: 'dev'
      target_platform_stage:
        description: 'Target Platform'
        required: true
        default: 'stage'
      target_platform_prod:
        description: 'Target Platform'
        required: true
        default: 'prod'        

jobs:
  build_dev:
    uses: ./.github/workflows/child.yml
    with: 
       target_platform: '${{ github.event.inputs.target_platform_dev }}'
    secrets: inherit

  build_stage:
    uses: ./.github/workflows/child.yml
    needs: build_dev
    with: 
       target_platform: '${{ github.event.inputs.target_platform_stage }}'
    secrets: inherit

  build_prod:
    uses: ./.github/workflows/child.yml
    needs: build_stage
    with: 
       target_platform: '${{ github.event.inputs.target_platform_prod }}'
    secrets: inherit   