
name: Stage Testing Gates

on:
    
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'Target Platform'
        required: true
        default: 'dev'
        type: choice
        options:
          - "dev"
          - "stage"
          - "prod"
      # environment:
      #   description: "Environment to run build against"
      #   type: environment
      #   required: true

jobs:
  stage_one:
    name: stage one - ${{ github.event.inputs.target_platform }}
    uses: ./.github/workflows/stage1.yml
    with: 
       target_platform: '${{ github.event.inputs.target_platform }}'
    secrets: inherit

  build_platform:
    name: deploy - ${{ github.event.inputs.target_platform }}
    needs: stage_one
    uses: ./.github/workflows/build.yml
    with: 
       target_platform: '${{ github.event.inputs.target_platform }}'
    secrets: inherit

  matrix_build:
    strategy:
      matrix:
          target: [dev, stage, prod]
    uses: ./.github/workflows/matrix.yml
    with:
      target: ${{ matrix.target }}
