
name: Stage Testing Gates

on:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'Target Platform'
        required: true
        default: 'dev'
        type: choice
        options:
          - "dev"
          - "stage"
          - "prod"
      # environment:
      #   description: "Environment to run build against"
      #   type: environment
      #   required: true

jobs:
  authenticate_platform:
    name: authenticate - ${{ github.event.inputs.target_platform }}
    uses: ./.github/workflows/stage1.yml
    with: 
       target_platform: '${{ github.event.inputs.target_platform }}'
    secrets: inherit

  build_platform:
    name: deploy - ${{ github.event.inputs.target_platform }}
    needs: authenticate_platform
    uses: ./.github/workflows/build.yml
    with: 
       target_platform: '${{ github.event.inputs.target_platform }}'
    secrets: inherit


