
name: build and deploy platform - parent

on:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'Target Platform'
        required: true
        options:
          - "dev"
          - "stage"
          - "prod"
        default: 'dev'

jobs:
  build_platform:
    uses: ./.github/workflows/child.yml
    with: 
       target_platform: '${{ github.event.inputs.target_platform }}'
    secrets: inherit