
name: build and deploy platform - parent

on:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'Target Platform'
        required: true
        default: 'dev'
        type: choice
        options:
          - "dev"
          - "stage"
          - "prod"
      environment:
        description: "Environment to run build against"
        type: environment
        required: true

jobs:
  build_platform:
    name: deploy - ${{ github.event.inputs.target_platform }}
    uses: ./.github/workflows/child.yml
    with: 
       target_platform: '${{ github.event.inputs.target_platform }}'
    secrets: inherit

