name: authenticate platform

on:
  workflow_call:
    inputs:
      target_platform:
        required: true
        type: string

jobs:
  build_platform:
    name: authenticate - ${{ github.event.inputs.target_platform }}
    runs-on: ubuntu-latest
    env:
      zone: ${{ github.event.inputs.target_platform }}
    steps:
      - name: Stage 1 Test
        run: |
          echo "Stage 1 workflow test"
          echo $zone





